services:
  slashvibeissue:
    build:
      context: .
      dockerfile: Dockerfile
    read_only: true
    image: slashvibeissue:latest
    container_name: slashvibeissue
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
    restart: on-failure:10
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./config.yaml:/config.yaml:ro
